#include<iostream.h>
#include<conio.h>
void main()
{ clrscr();
int ch;
cout<<"Enter any number of your choice:\n1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 0\n................................................\n";
cin>>ch;
switch(ch)
{
  case 1:cout<<"One";
  break;

  case 2:cout<<"Two";
  break;

  case 3:cout<<"Three";
  break;

  case 4:cout<<"Four";
  break;

  case 5:cout<<"Five";
  break;

  case 6:cout<<"Six";
  break;

  case 7:cout<<"Seven";
  break;


  case 8:cout<<"Eight";
  break;

  case 9:cout<<"Nine";
  break;

  case 0:cout<<"Zero";
  break;
  }
  getch();
  }